In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random


In [ ]:
class Process:
    def __init__(self,name,arrival_time,burst_time,priority=0):
        self.name=name
        self.arrival_time=arrival_time
        self.burst_time=burst_time
        self.priority=priority
        self.remaining_time=burst_time
        self.start_time=0
        self.end_time=0
        self.waiting_time=0
        self.turnaround_time=0
        self.is_completed=False
        self.is_started = False
    
    def complete(self,t):
        self.end_time=t
        self.turnaround_time=self.end_time-self.arrival_time
        self.waiting_time=self.turnaround_time-self.burst_time
        self.is_completed=True
    
class Queue:
    def __init__(self,MLFQ,max_burst_time,priority):
        self.max_burst_time = max_burst_time
        self.priority = priority
        self.processes = []
        self.next_queue = None        
        self.last_queue = None
        self.is_completed = True
        self.MLFQ = MLFQ
        self.last = False

    def add_process(self,process):
        self.processes.append(process)
        self.is_completed = False

    def remove_process(self):
        self.processes.pop(0)
        if len(self.processes) == 0:
            self.is_completed = True
        
    def get_process(self):
        return self.processes[0]

    def complete_process(self):
        

    def run(self,t):
        for i in range(t):
            process = self.get_process()
            if not process.is_started:
                process.start_time = self.MLFQ.time
                process.is_started = True

            if self.last:
                while process.remaining_time > 0:
                    self.MLFQ.time += 1
                    process.remaining_time -= 1
                    process.complete(self.MLFQ.time)
                    self.MLFQ.complete_process.append(process)
                    self.remove_process()
                    break
            else:
                for _ in range(self.max_burst_time):
                    self.MLFQ.time += 1
                    if self.is_completed:
                        return
                    process.remaining_time -= 1
                    if process.remaining_time == 0:
                        process.complete(self.MLFQ.time)
                        self.MLFQ.complete_process.append(process)
                        self.remove_process()
                        break
                if process.remaining_time > 0:
                    self.next_queue.add_process(process)
                    self.remove_process()


class MLFQ:                         #Multilevel Feedback Queue Scheduling
    def __init__(self,queues,processes,end):
        self.init_processes(processes)
        self.init_queues(queues)
        self.time = 0
        self.complete_processes = []
        self.end = end

    def init_queues(self,queues):
        self.queues = []
        for q in queues:
            self.add_queue(Queue(self,q,0))

    def add_queue(self,queue):
        if len(self.queues) == 0:
            self.queues.append(queue)
            self.queues[0].last = True
        else:
            self.queues.append(queue)
            self.queues[-1].last = True
            self.queues[-2].last = False
            self.queues[-2].next_queue = queue

    def init_processes(self,processes):
        self.processes = []
        for p in range(len(processes)):
            process = Process(p, processes[p][0],processes[p][1],0)
            self.processes.append(process)

    def check_processes(self):
        if self.time == self.processes[0].arrival_time:
            self.queues[0].add_process(self.processes[0])
            self.processes.pop(0)

    def check_higher_priority_queue(self):
        for queue in self.queues:
            if len(queue.processes) > 0:
                return queue
            else:
                return None

    def run(self):
        self.current_queue = self.queues[0]
        self.current_process = None
        self.cpu_state = 'free'
        while self.time <= self.end:
            self.check_processes()
            if self.cpu_state == 'free':
                self.current_queue = self.get_highest_priority_queue()
                if self.current_queue is not None:
                    self.cpu_state = 'busy'
                    tuen_time = 0
                    while tuen_time <= self.current_queue.max_burst_time:
                        self.current_process = self.current_queue.get_process()
                        self.current_process.remaining_time -= 1
                    
                        self.time += 1
                        if self.current_process.remaining_time == 0:
                            self.current_queue.complete_process()

def generate_process(start,end,number_of_processes,max_burst_time):    
    arrival_times = np.asarray(random.sample(range(start,end),number_of_processes))
    burst_times = np.asarray(random.sample(range(1,max_burst_time),number_of_processes))
    arrival_times = np.sort(arrival_times)
    process =  np.array(list((zip(arrival_times,burst_times)))).reshape(number_of_processes,2)
    return process
    


def main(start,end,number_of_processes,max_burst_time):
    processes = generate_process(start,end,number_of_processes,max_burst_time)
    mlfq = MLFQ([4,8,16],processes,end+max_burst_time)



In [3]:
import random
import numpy as np
np.sort(random.sample(range(0, 1000), 10))

array([ 38,  46, 206, 250, 716, 726, 826, 847, 864, 872])

In [14]:
a = np.asarray(random.sample(range(0, 1000), 10))
b = np.asarray(random.sample(range(0, 1000), 10))
a


array([876,  43, 783, 644, 107, 215, 808, 796, 724,  94])

In [22]:
c = np.concatenate((a,b))
c.reshape(2,-1)

array([[876,  43, 783, 644, 107, 215, 808, 796, 724,  94],
       [613, 789, 367, 158, 816, 512, 621, 124, 535, 141]])

In [56]:
np.array(list((zip(a,b)))).reshape(10,2)

array([[876, 613],
       [ 43, 789],
       [783, 367],
       [644, 158],
       [107, 816],
       [215, 512],
       [808, 621],
       [796, 124],
       [724, 535],
       [ 94, 141]])